### ISSUE TITLE
Blank page on loading index

### ISSUE THREAD

**Issue by jason88fr** [elias123tre/bitwarden_find_duplicates#7]
I"m on Arch.

The script seems slow but I think that may be because of the number of entries in my vault.

Upon completion however, it loads a blank page.

How do I proceed and what information do you require from me?

**Comment by elias123tre** [comment]
To further troubleshoot, you could open the developer console and look for any error messages or warnings and add them as a comment here. [Instructions on how to open the console in your browser](https://screenful.com/how-to-open-the-browser-console.)

**Comment by jason88fr** [comment]
logins.js:1 Uncaught SyntaxError: missing ) after argument list
index.html:132 Uncaught ReferenceError: logins is not defined
    at Proxy.data (index.html:132:29)
    at Oo (vue.global.prod.js:1:32870)
    at ns (vue.global.prod.js:1:59981)
    at vue.global.prod.js:1:47201
    at vue.global.prod.js:1:47209
    at A (vue.global.prod.js:1:47228)
    at R (vue.global.prod.js:1:45484)
    at m (vue.global.prod.js:1:42523)
    at ee (vue.global.prod.js:1:53761)
    at mount (vue.global.prod.js:1:37982)

**Comment by elias123tre** [comment]
@jason88fr
I published a new release ([v1.2.0](https://github.com/elias123tre/bitwarden_find_duplicates/releases/tag/v1.2.0)) that hopefully fixes your issue (and adds more features!). Redownload the script and reply if it works now.

**Comment by jason88fr** [comment]
Thank you!

My issue is fixed as of version 1.2.0!
